language: java
sudo: required
jdk:
- openjdk8
install: false
script:
- export PROJECT_NAME=KickIdlePlayer
- git clone https://$Github_token@github.com/Ghost-chu/$PROJECT_NAME.git
- cd $PROJECT_NAME
- mvn clean
- mvn -T 4 install
after_success:
- rm -rf push
- mkdir push
- cp -r ./target/*.jar ./push/
- rm -f ./target/original-*.jar
- git clone https://$Github_token@github.com/Ghost-chu/BinaryRepository.git
- mkdir -p ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER
- mkdir -p ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/target
- cp -r ./target/* ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/target
- echo -e "== Built by Travis-CI ==\nBuild Number [$TRAVIS_BUILD_NUMBER]\nBuild Type
  [$TRAVIS_EVENT_TYPE]\nTag [$TRAVIS_TAG]\nCommit [$TRAVIS_COMMIT] - [$TRAVIS_COMMIT_MESSAGE]"
  > ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/BUILDINFO
- cd BinaryRepository
- git add .
- git commit -m "Auto update by Bot"
- git push --force
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  #Use travis client command line "travis setup release --force" gen the api_key and replace the secure.
  api_key:
    secure: yAvTSpCNNH7l3gU2g+0vM+lbCEvFGuNwOoZ/8NavpUsi2od21YgVHDn+TE1xBH2jqd6WGFfPIGlpJ493xeK/cPA7AeO41sGe93mWeQ/VDZXT5c5C5Ydsh8PMoCeLgaT+bT6dJLE9yljgGwPc9EVFYMkizppsgBGZ9DJLnDsBraEwc9sHAJRy+y8LysKw4XF3BQpaF1V4EUdpgI2IMgEBt7e07KBdsQrgh8LvZqVqWs7wTQBCnjHJkRy/RrpOoNKvh509r1KZIb6F6KhyLVJGDlaYR7IVo2ck+rK0Tx0CmuIsgTe4kK4lnWSYbmjfUYZx0FOnn+TM03cYaDIbR84D1mgzR+vqMjHIg+KfTsI4Drsllfozk5pXb5msoP/mfxNzeXElxEVcxO5ffAjQ42FfY1EaPUcbYClOt6jHKsIIfFNIgkBm3UDD2hTNjOT3Z5O0hCTvaC+gi30hrBMZBp/lR99hCPWNXSmOuBTxeWdTKpvl9CXtmg+H8ihev0tOpYt7JnAT/YPnen3S3QT6Velavk5PyEphcXUkaf5A+Zjnj1SD1k2mq8UTgRBP6acdYZ6ueMFWcNahlgtCDku/FdlvaUgBVeIoJ9MEHcRPGcaH9JmWW9/R7np1lsFxC3Cex1DRCOp5wuBNUKv2CkQQlfAz3qNQxIsD+TA4EAOWyyqqrbA=
  file:
    - ./push/*
  file_glob: true
  on:
    repo: Ghost-chu/$PROJECT_NAME
    tags: true
  overwrite: true
